workflows:
  native-android-project:
    name: Android ZIP Project Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_VERSION: "17"
      node: "18"  # أضف Node.js
    scripts:
      - name: Extract project ZIP
        script: |
          ZIP_FILE=$(find . -name "*.zip" -print -quit)
          if [ -z "$ZIP_FILE" ]; then
            echo "No ZIP file found in the repository."
            exit 1
          fi
          echo "Extracting $ZIP_FILE..."
          unzip -o "$ZIP_FILE" -d .
      - name: Locate project root
        script: |
          PROJECT_ROOT=$(find . -name gradlew -print -quit | xargs dirname)
          if [ -z "$PROJECT_ROOT" ]; then
            echo "gradlew not found!"
            exit 1
          fi
          cd "$PROJECT_ROOT"
          chmod +x gradlew
          echo "Project root: $PROJECT_ROOT"
      - name: Install Node.js dependencies
        script: |
          if [ -f package.json ]; then
            echo "Installing npm dependencies..."
            npm install
          else
            echo "No package.json found, skipping npm install"
          fi
      - name: Sync Capacitor
        script: |
          if [ -f package.json ]; then
            echo "Running Capacitor sync..."
            npx cap sync android
          else
            echo "No Capacitor project, skipping sync"
          fi
      - name: Build Android Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - "**/build/outputs/apk/release/*.apk"
    publishing:
      email:
        recipients:
          - your-email@example.com
