workflows:
  native-android-project:
    name: Native Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - magic_variables
      vars:
        JAVA_VERSION: "17"
    scripts:
      - name: Set permissions for gradlew
        script: | 
          chmod +x gradlew
      - name: Build Android Release APK
        script: | 
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
          
